# Generated by Django 4.2.17 on 2024-12-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_district_alter_listing_list_date_and_more'),
        ('contacts', '0003_contact_ct_title_alter_contact_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Ct_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing'),
        ),
    ]
