# Generated by Django 4.2.17 on 2024-12-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_ct_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Ct_title',
        ),
    ]
