# Generated by Django 4.2.17 on 2024-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_ct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor',
            field=models.CharField(default='Wendy Tan', max_length=100),
            preserve_default=False,
        ),
    ]
