# Generated by Django 4.2.17 on 2025-01-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_district_alter_listing_list_date_and_more'),
        ('contacts', '0006_contact_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='realtor',
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
