# Generated by Django 4.2.17 on 2024-12-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedrooms',
            new_name='bathrooms',
        ),
    ]
