# Generated by Django 4.2.17 on 2024-12-28 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_bedroom_listing_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('_', 'All Districts'), ('Islands', 'Islands'), ('KwaiTsing', 'Kwai Tsing'), ('North', 'North'), ('SaiKung', 'Sai Kung'), ('Shatin', 'Sha Tin'), ('TaiPo', 'Tai Po'), ('TsuenWan', 'Tsuen Wan'), ('TuenMun', 'Tuen Mun'), ('YuenLong', 'Yuen Long'), ('KowloonCity', 'Kowloon City'), ('KwunTong', 'Kwun Tong'), ('ShamShuiPo', 'Sham Shui Po'), ('WongTaiSin', 'Wong Tai Sin'), ('YauTsimMong', 'Yau Tsim Mong'), ('Central&Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('WanChai', 'Wan Chai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
